.TH "Gambas" "1" "March 2012" "Debian" ""

.SH "NAME"
gambas \- Integrated Development Environment.

.SH "SYNOPSIS"
.B gambas
[<project file or project directory>]

.SH "DESCRIPTION"
Gambas is, before all, a Basic language with object extensions.
A program written with Gambas is a set of files. Each file describes
a class, in terms of object programming. The class files are compiled,
then executed by an interpreter. From this point of view, it is
very inspired by Java.

Gambas is made up of the following programs:

    * A compiler.
    * An interpreter.
    * An archiver.
    * A graphical user interface component.
    * A development environment.

The development environment is written with Gambas itself, so that I can
show the abilities of the language. And it is very useful for debugging!

\fBgambas\fR starts the Integrated Development Environment.

.SH "AVAILABILITY"
Updated source code and most documentation about gambas can be found at http://gambas.sf.net,
documentation about the language is at http://www.binara.com/gambas\-wiki,
documentation in the spanish language is at http://gambas.gnulinex.org.

.SH "REPORTING BUGS"
Report bugs to
<gambas@users.sourceforge.net>.

.SH "COPYRIGHT"
Copyright\(co 2002, 2012 Benoit Minisini <gambas@users.sourceforge.net;
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
