.TH "gbw3" "1" "July 2012" "Debian" "User Commands"

.SH "NAME"
gbw3 \- GAMBAS Web Page Interpeter

.SH "SYNOPSIS"
.B gbw3
[\fIoptions\fR] [<server page file>]


.SH "DESCRIPTION"
Gambas is a free development environment based on a Basic interpreter with object extensions, like Visual Basic(tm) (but it is NOT a clone!).
With Gambas, you can quickly design your program GUI, access MySQL or PostgreSQL databases, pilot KDE applications with DCOP, translate your program into many languages, and so on...

\fBgbw3\fR is the special interpreter that allows you to execute Gambas Server Pages. Not a lot is known about how to use it.

.SH "OPTIONS"
.TP
\fB\-c\fR, \fB\-\-nocache\fR
force the script compilation (do not check cache)
.TP
\fB\-v\fR, \fB\-\-verbose\fR
be verbose
.TP
\fB\-V\fR, \fB\-\-version\fR
display version information and exit
.TP
\fB\-L\fR, \fB\-\-license\fR
display license and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit


.SH "AVAILABILITY"
The latest version of Gambas can always be obtained from
\fBhttp://gambas.sf.net\fR.


.SH "REPORTING BUGS"
Report bugs to
<gambas@users.sourceforge.net>.

.SH "COPYRIGHT"
Copyright\(co 2002, 2012 Benoit Minisini <gambas@users.sourceforge.net;
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
